name: Dela Anthonio

title: Dela Anthonio

email: dela.anthonio@pm.me

logo: https://delaanthonio.github.io/img/technologist.png

description: >-
  Dela Anthonio | Software Engineer

baseurl: ""

url: https://delaanthonio.github.io/

cover: https://delaanthonio.github.io/img/headshot.jpg

social:
  - twitter: "@delaanthonio"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
